### PR TITLE
Correct order of table creation

### PR DESCRIPTION
**Pull request by ottenhoff**
Because of FKs ... need to create tables in order

### CODE REVIEW

**Comment by ottenhoff** [comment]
Anyone here?

**Comment by master-bob** [comment]
Someone with write access will need to merge this.

**Comment by master-bob** [comment]
@bjones86 I think you have write access, can you merge this?

**Comment by master-bob** [comment]
Thank you.

**Comment by bjones86** [comment]
Not a problem. I think I've given you an invite to have 'write' access to this repo, seeing as you're effectively the authority on this tool.

**Pull request merged**
