### PR TITLE
Check for Student role based on section.role.student permission instead of the role name 

### PR DESCRIPTION
**Pull request by ottenhoff**
This code is untested. This is meant to address #32 

CC: @davidpbauer

### CODE REVIEW

**Comment by davidpbauer** [comment]
Thanks, @ottenhoff. It looks to me like this would address the issue because any role could be assigned section.role.student.

Our new developer, Joe Kozar (@jkozar2) has started working on Attendance (starting with addressing the performance issues) and can take a look at this as well.

**Comment by ottenhoff** [comment]
Hi @jkozar2, any thoughts on this PR?

**Comment by jkozar2** [comment]
This looks good to me! Do I need to merge this or would you like to do it?

**Comment by jkozar2** [comment]
My mistake, I did not see that it was already merged. Sorry for the delay.

**Pull request merged**
